export enum ExceptionCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  NOT_CARRY_TOKEN = ' NOT_CARRY_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INAVLID_DATA = 'INAVLID_DATA',
  THIS_USER_NOT_HAVE_PERMISSION = 'THIS_USER_NOT_HAVE_PERMISSION',
}
